### PR TITLE
Added some sanitization functions so code will pass PHP Code Sniffer scans

### PR DESCRIPTION
**Pull request by mphillips**
I'm using this plugin in a site that requires PHP Code Sniffer scans to pass before deployments. I needed to add some sanitization functions for that to happen. Can they be merged into master and released in Wordpress' repo?

### CODE REVIEW

**Comment by johnbillion** [comment]
Hi Michael,

As you can see, these are false negatives in the code sniffer. The output here is wrapped in `esc_html__()` and so it is safe.

Which code standards are you using for your sniffing? Using `WordPress-VIP` I get a bunch of other errors too. Do these not also prevent the deployment?

**Comment by johnbillion** [comment]
Rather than escaping twice, it looks like we can get around the sniffing problem by switching to:

`echo esc_html( sprintf( __( ... ) ) );`

**Comment by mphillips** [comment]
I'm just using the WordPress-Extra ruleset here: https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards

For code like this:

```
printf( esc_html__( 'Switched to %1$s (%2$s).', 'user-switching' ), $user->display_name, $user->user_login );
```

I *think* it's flagging them because $user->display_name is going to be inserted into the string *after* the first printf argument is escaped. $user->display_name needed to be escaped too since it could contain unsafe code.

But you're right that moving esc_html() outside of sprintf() will prevent escaping twice. I updated the pull request with those changes. :)

Thanks!

**Comment by johnbillion** [comment]
> I think it's flagging them because $user->display_name is going to be inserted into the string after the first printf argument is escaped.

Nice catch. I'd somehow missed that. I retract my previous moanings about the codesniffer!

**Comment by johnbillion** [comment]
Thanks Michael, I squashed those commits and this is now in the latest version of the plugin which has just been released.

**Comment by mphillips** [comment]
Thanks John!

**Pull request closed without merging**
